### ISSUE TITLE
notification for a-game-starts should include a link that specifies the color of the player

### ISSUE THREAD

**Issue by endrawes0** [endrawes0/Chesster#112]
so you do not need to flip the board

**Comment by lakinwecker** [comment]
This is a great idea.

I think the subscription system will have to be updated to support it, as it currently does not pass along the source of the event.  Part of the reason it does this is that it does its best to only send one event despite how many subscription records dictated it. So if you are subscribed to the same event for both players and for the board they are on and for the team they are on, then you don't get three events. you only get one. And the source would be ambiguous.  

However, in the case where you are only subscribed to one of them, then yes, this is a good idea.

**Comment by kostasvl-github** [comment]
I think this issue is fixed .

**Comment by lakinwecker** [comment]
I am pretty sure this one is not fixed. I have been meaning to fix it, but
have not.

**Comment by kostasvl-github** [comment]
I thought that @chesster should send the colours in the DM of the players .

**Comment by lakinwecker** [comment]
This is about the link to the game. It should link to it such that ylthe
viewer is viewing from the right side of the board.

Lakin
